import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
sub = ('tam' , 'eng' , 'mat' , 'sci' , 'soc')
manoj = (50,77,67,88,70)
plt.plot(sub,manoj ,label = 'manoj')
jonam = (60,66,77,60,90)
plt.plot(sub,jonam , linewidth = 3,label = 'jonam')
plt.title("students marks")
plt.xlabel("S U B J E C T S")
plt.ylabel("M A R K S")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

